"""Add user mm_per_pixel and detection size/weight/grade

Revision ID: 518703374959
Revises: 
Create Date: 2026-04-26 10:47:30.615238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '518703374959'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detection_boxes', sa.Column('size_category', sa.String(length=20), nullable=True))
    op.add_column('detection_boxes', sa.Column('weight_g', sa.Float(), nullable=True))
    op.add_column('detection_boxes', sa.Column('grade', sa.String(length=10), nullable=True))
    # Add mm_per_pixel as nullable first, then set default for existing users
    op.add_column('users', sa.Column('mm_per_pixel', sa.Float(), nullable=True))
    op.execute("UPDATE users SET mm_per_pixel = 0.5 WHERE mm_per_pixel IS NULL")
    op.alter_column('users', 'mm_per_pixel', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mm_per_pixel')
    op.drop_column('detection_boxes', 'grade')
    op.drop_column('detection_boxes', 'weight_g')
    op.drop_column('detection_boxes', 'size_category')
    # ### end Alembic commands ###